services:
  # Serviço do Backend
  - type: web
    name: portifolio-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --no-package-lock
      npm run build:render
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portifolio-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://portifolio-frontend.onrender.com
      - key: VITE_API_URL
        value: https://portifolio-backend.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: ENABLE_COMPRESSION
        value: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://portifolio-frontend.onrender.com
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: UV_THREADPOOL_SIZE
        value: 32
      - key: CACHE_TTL
        value: 3600
      - key: RENDER_EXTERNAL_URL
        value: https://portifolio-backend.onrender.com
      - key: RENDER_EXTERNAL_HOSTNAME
        value: portifolio-backend.onrender.com

  # Serviço do Frontend
  - type: web
    name: portifolio-frontend
    env: static
    buildCommand: |
      cd client
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --no-package-lock
      npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://portifolio-backend.onrender.com

databases:
  - name: portifolio-db
    databaseName: portifolio
    plan: free 