services:
  # Serviço do Backend
  - type: web
    name: portifolio-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portifolio-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://portifolio-frontend.onrender.com
      - key: VITE_API_URL
        value: https://portifolio-backend.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: ENABLE_COMPRESSION
        value: true
      - key: PORT
        value: 10000

  # Serviço do Frontend
  - type: web
    name: portifolio-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://portifolio-backend.onrender.com

databases:
  - name: portifolio-db
    databaseName: portifolio
    plan: free 